#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=8

# Semua nilai .env ditulis ke .env.local, bukan .env, karena itu yang dibaca Next.js.
# Pustaka di atas memberi nilai bawaan ".env"; hanya nilai bawaan itu yang diganti,
# supaya `ENV_FILE=... ./setup-supabase.sh` tetap bisa dipakai untuk uji coba.
[[ "$ENV_FILE" == ".env" ]] && ENV_FILE=".env.local"

# Berkas SQL terlalu panjang untuk diketik ulang, jadi wizard menyalinnya ke papan
# klip dan cukup ditempel di SQL Editor. Tanpa papan klip, wizard menyebutkan
# berkasnya supaya bisa dibuka manual.
CLIP_CMD=""
for c in wl-copy pbcopy xclip xsel clip.exe; do
  if command -v "$c" >/dev/null 2>&1; then CLIP_CMD="$c"; break; fi
done

copy_clip() {
  local file="$1"
  case "$CLIP_CMD" in
    wl-copy)  wl-copy < "$file" ;;
    pbcopy)   pbcopy  < "$file" ;;
    xclip)    xclip -selection clipboard < "$file" ;;
    xsel)     xsel --clipboard --input   < "$file" ;;
    clip.exe) clip.exe < "$file" ;;
    *)        return 1 ;;
  esac
}

# offer_sql FILE LABEL: salin ke papan klip, atau jelaskan cara membukanya sendiri.
offer_sql() {
  local file="$1" label="$2"
  if [[ ! -f "$file" ]]; then
    warn "berkas $file tidak ditemukan; jalankan wizard dari akar proyek"
    exit 1
  fi
  if copy_clip "$file" 2>/dev/null; then
    local kb=$(( ( $(wc -c < "$file") + 1023 ) / 1024 ))
    printf '  %s✓ disalin%s %s (%s KB) ke papan klip\n' \
      "$GREEN" "$RESET" "$label" "$kb"
    step "Tempel di SQL Editor dengan Ctrl-V, lalu tekan Run."
  else
    SKIPPED+=("salin isi $file ke SQL Editor secara manual")
    warn "papan klip tidak tersedia di sistem ini"
    step "Buka berkas $file, salin seluruh isinya, tempel di SQL Editor, tekan Run."
  fi
}

# ask_until KEY "Prompt" REGEX "Petunjuk": mengulang sampai jawabannya berbentuk benar.
# Salah tempel di sini baru ketahuan berjam-jam kemudian sebagai "Failed to fetch",
# jadi lebih baik ditolak di tempat.
ask_until() {
  local key="$1" prompt="$2" re="$3" hint="$4" tries=0
  while true; do
    # Tanpa batas ini, masukan yang habis (misal wizard dijalankan dari pipa)
    # membuat `read` gagal diam-diam dan gelung ini berputar selamanya.
    if (( tries++ >= 5 )); then
      warn "Lima kali masukan tidak sesuai. Wizard dihentikan."
      note "Jalankan ulang: ./scripts/setup-supabase.sh"
      exit 1
    fi
    ask "$key" "$prompt"
    local val="${!key}"
    val="${val#"${val%%[![:space:]]*}"}"      # buang spasi di depan
    val="${val%"${val##*[![:space:]]}"}"      # dan di belakang
    printf -v "$key" '%s' "$val"
    [[ "$val" =~ $re ]] && return 0
    warn "$hint"
  done
}

# Supabase CLI dijalankan lewat npx/bunx supaya tidak perlu dipasang global.
# Disimpan sebagai larik, bukan string, supaya argumennya tidak dipecah ulang.
SUPA=()
if   command -v supabase >/dev/null 2>&1; then SUPA=(supabase)
elif command -v npx      >/dev/null 2>&1; then SUPA=(npx --yes supabase@latest)
elif command -v bunx     >/dev/null 2>&1; then SUPA=(bunx supabase@latest)
fi
SUPA_LABEL="${SUPA[*]}"

banner "Penyiapan Supabase · E-Modul Gendang Beleq"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prasyarat"
say "Wizard ini menyiapkan penyimpanan nilai siswa untuk modul ini."
say ""
say "Yang kamu butuhkan:"
step "Akun Supabase (gratis) — https://supabase.com"
step "Peramban yang sudah login ke akun itu"
step "Waktu sekitar sepuluh menit"
say ""
if (( ${#SUPA[@]} )); then
  note "Supabase CLI akan dijalankan sebagai: $SUPA_LABEL"
else
  warn "node maupun bun tidak ditemukan, jadi Edge Function tidak bisa di-deploy dari sini."
  SKIPPED+=("deploy Edge Function 'submit': pasang Supabase CLI lalu jalankan 'supabase functions deploy submit'")
fi
if [[ -z "$CLIP_CMD" ]]; then
  warn "Papan klip tidak tersedia; berkas SQL nanti kamu salin sendiri."
fi
say ""
note "Berhenti kapan saja dengan Ctrl-C. Nilai yang sudah tersimpan di $ENV_FILE akan diingat saat wizard dijalankan ulang."
pause "Tekan Enter untuk mulai."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Buat proyek Supabase"
say "Satu proyek menampung seluruh kelas, jawaban, dan nilai modul ini."
open_url "https://supabase.com/dashboard/projects"
step "Klik 'New project'."
step "Beri nama, misalnya 'emodul-gendang-beleq'."
step "Pilih Region 'Southeast Asia (Singapore)' — paling dekat dari Lombok."
step "Buat Database Password dan SIMPAN di tempat aman."
step "Klik 'Create new project', lalu tunggu sampai statusnya hijau (1–2 menit)."
pause "Tekan Enter kalau proyeknya sudah jadi."

say ""
say "Sekarang ambil dua nilai dari halaman API."
open_url "https://supabase.com/dashboard/project/_/settings/api"
step "Salin 'Project URL'. Bentuknya https://xxxxxxxx.supabase.co"
ask_until NEXT_PUBLIC_SUPABASE_URL "Tempel Project URL:" \
  '^https://[a-zA-Z0-9-]+\.supabase\.(co|in)/?$' \
  "Itu bukan Project URL. Yang benar berbentuk https://xxxxxxxx.supabase.co"
say ""
step "Di bagian API Keys, salin kunci yang berlabel 'anon' / 'public'"
step "(pada dashboard baru namanya 'publishable'). JANGAN kunci service_role."
ask_until NEXT_PUBLIC_SUPABASE_ANON_KEY "Tempel anon key:" \
  '^(eyJ[A-Za-z0-9_.-]{30,}|sb_publishable_[A-Za-z0-9_-]{10,})$' \
  "Itu belum tampak seperti anon key. Kunci lama diawali eyJ, kunci baru diawali sb_publishable_"

# Buang garis miring di ujung supaya URL tidak jadi ganda garis miring.
NEXT_PUBLIC_SUPABASE_URL="${NEXT_PUBLIC_SUPABASE_URL%/}"

# Kunci service_role melewati SELURUH aturan keamanan baris. Kalau ia sampai masuk
# ke .env.local, ia ikut ke bundel peramban setiap siswa, dan seluruh nilai di
# database bisa diubah siapa pun.
#
# Peran itu tidak pernah tampak mentah di dalam JWT — ia ada di dalam payload yang
# ter-base64. Jadi payload-nya harus dibuka dulu sebelum diperiksa.
jwt_role() {
  local payload="${1#*.}"; payload="${payload%%.*}"
  [[ "$payload" == "$1" ]] && return 1                 # bukan JWT tiga bagian
  # base64url -> base64, lalu ditambal '=' supaya panjangnya kelipatan empat
  payload="${payload//-/+}"; payload="${payload//_//}"
  while (( ${#payload} % 4 )); do payload+="="; done
  printf '%s' "$payload" | base64 -d 2>/dev/null || true
}
KEY_CLAIMS="$(jwt_role "$NEXT_PUBLIC_SUPABASE_ANON_KEY")"
if [[ "$KEY_CLAIMS" == *'"service_role"'* || "$NEXT_PUBLIC_SUPABASE_ANON_KEY" == sb_secret_* ]]; then
  warn "Itu kunci service_role, bukan anon key."
  say "Kunci itu melewati semua aturan keamanan dan tidak boleh sampai ke peramban siswa."
  say "Jalankan wizard lagi, lalu salin kunci yang berlabel anon / public."
  exit 1
fi
if [[ -n "$KEY_CLAIMS" && "$KEY_CLAIMS" != *'"anon"'* ]]; then
  warn "Kunci itu bukan peran anon. Periksa lagi kalau siswa nanti tidak bisa bergabung."
fi
write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"

# Ref proyek diambil dari URL-nya, jadi tidak perlu ditanyakan lagi.
PROJECT_REF="${NEXT_PUBLIC_SUPABASE_URL#https://}"
PROJECT_REF="${PROJECT_REF%%.supabase.co*}"
if [[ -z "$PROJECT_REF" || "$PROJECT_REF" == "$NEXT_PUBLIC_SUPABASE_URL" ]]; then
  warn "Tidak bisa membaca ref proyek dari URL itu."
  ask PROJECT_REF "Ketik ref proyek (bagian sebelum .supabase.co):"
fi
note "Ref proyek: $PROJECT_REF"
DASH="https://supabase.com/dashboard/project/$PROJECT_REF"
pause "Tekan Enter untuk lanjut."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Aktifkan anonymous sign-in"
say "Siswa masuk lewat kode kelas, bukan email dan kata sandi."
say "Di belakang layar tiap perangkat tetap perlu identitas asli agar aturan"
say "keamanan baris bisa mengikat jawaban ke pemiliknya. Itu gunanya fitur ini."
say ""
warn "Tanpa langkah ini siswa tidak akan bisa bergabung ke kelas sama sekali."
open_url "$DASH/auth/providers"
step "Buka Authentication → Sign In / Providers."
step "Cari 'Allow anonymous sign-ins' (di sebagian versi ada di bagian User Signups)."
step "Nyalakan sakelarnya, lalu Save."
pause "Tekan Enter kalau sudah menyala."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Jalankan migrasi skema"
say "Membuat tabel kelas, siswa, jawaban, LKPD, dan seluruh aturan keamanan baris."
open_url "$DASH/sql/new"
offer_sql "supabase/migrations/0001_init.sql" "migrasi skema"
say ""
note "Hasil yang benar: 'Success. No rows returned'."
warn "Kalau muncul 'already exists', berarti migrasi ini sudah pernah jalan. Aman, lanjut saja."
pause "Tekan Enter kalau SQL-nya sudah dijalankan."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Isi konten bawaan"
say "Mengisi draf guru dengan seluruh materi, glosarium, dan 7 bank soal bawaan,"
say "lengkap dengan kunci jawabannya. Kunci ini hanya ada di server."
open_url "$DASH/sql/new"
offer_sql "supabase/migrations/0002_seed_content.sql" "konten bawaan"
say ""
note "Berkas ini besar, jadi Run-nya bisa berjalan beberapa detik."
pause "Tekan Enter kalau sudah selesai."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Buat akun guru"
say "Akun ini menggantikan PIN lama. Hanya akun yang terdaftar di tabel"
say "'teachers' yang bisa membuka panel dan melihat nilai siswa."
open_url "$DASH/auth/users"
step "Klik 'Add user' → 'Create new user'."
step "Isi email dan kata sandi guru."
step "Centang 'Auto Confirm User' supaya tidak perlu verifikasi email."
step "Klik Create user."
say ""
step "Klik baris pengguna yang baru dibuat, lalu salin UID-nya."
step "Bentuknya seperti 3f9a1c22-7b4e-4a10-9c3d-8e5f2a1b6d40"
ask_until GURU_UUID "Tempel UID akun guru:" \
  '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' \
  "Itu bukan UID. Bentuknya 8-4-4-4-12 huruf dan angka, dipisah tanda hubung."
ask_until GURU_NAMA "Nama guru yang akan tampil di panel:" '^.+$' \
  "Nama tidak boleh kosong."

# Kutip tunggal digandakan supaya nama seperti O'Neill tidak mematahkan SQL-nya.
GURU_NAMA_SQL="${GURU_NAMA//\'/\'\'}"
TEACHER_SQL="$(mktemp)"
trap 'rm -f "$TEACHER_SQL"' EXIT
cat > "$TEACHER_SQL" <<SQL
-- Mendaftarkan akun guru. Dijalankan sekali saja.
insert into teachers (auth_uid, nama)
values ('$GURU_UUID', '$GURU_NAMA_SQL')
on conflict (auth_uid) do update set nama = excluded.nama;
SQL

say ""
open_url "$DASH/sql/new"
offer_sql "$TEACHER_SQL" "pendaftaran guru"
pause "Tekan Enter kalau sudah dijalankan."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Deploy Edge Function 'submit'"
say "Fungsi inilah yang menilai jawaban siswa. Kunci jawaban hanya dibaca di"
say "sini, tidak pernah dikirim ke peramban siswa."
say ""
if (( ${#SUPA[@]} == 0 )); then
  warn "Tidak ada node/bun/supabase di sistem ini, jadi langkah ini dilewati."
  note "Nanti jalankan sendiri: supabase functions deploy submit --project-ref $PROJECT_REF"
  pause
else
  say "Wizard akan menjalankan tiga perintah. Yang pertama membuka peramban."
  note "  $SUPA_LABEL login"
  note "  $SUPA_LABEL link --project-ref $PROJECT_REF"
  note "  $SUPA_LABEL functions deploy submit"
  say ""
  warn "Perintah 'link' bisa menanyakan Database Password yang tadi kamu simpan."
  say ""
  if confirm "Jalankan sekarang?"; then
    say ""
    if ! "${SUPA[@]}" login; then
      warn "Login gagal."
      SKIPPED+=("deploy Edge Function: jalankan '$SUPA_LABEL login' lalu deploy")
    elif ! "${SUPA[@]}" link --project-ref "$PROJECT_REF"; then
      warn "Link ke proyek gagal."
      SKIPPED+=("deploy Edge Function: jalankan '$SUPA_LABEL link --project-ref $PROJECT_REF' lalu deploy")
    elif ! "${SUPA[@]}" functions deploy submit; then
      warn "Deploy gagal."
      SKIPPED+=("deploy Edge Function: jalankan '$SUPA_LABEL functions deploy submit'")
    else
      printf '  %s✓%s Edge Function submit aktif\n' "$GREEN" "$RESET"
    fi
  else
    SKIPPED+=("deploy Edge Function: $SUPA_LABEL functions deploy submit --project-ref $PROJECT_REF")
    note "Dilewati. Tanpa fungsi ini jawaban kuis tidak bisa dinilai."
  fi
  pause "Tekan Enter untuk lanjut."
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Periksa hasilnya"
say "Menjalankan pemeriksaan mandiri proyek."
say ""
if command -v bun >/dev/null 2>&1; then
  if bun run test; then
    printf '  %s✓%s mesin penilaian dan pemisahan kunci jawaban lolos uji\n' "$GREEN" "$RESET"
  else
    warn "Ada uji yang gagal. Periksa keluarannya di atas."
  fi
else
  note "bun tidak ada; lewati uji."
fi
say ""
say "Langkah terakhir, dan ini kamu lakukan di modulnya:"
step "Jalankan: bun run dev"
step "Buka http://localhost:3000 lalu tekan 'Panel Guru'."
step "Masuk dengan email dan kata sandi guru yang tadi dibuat."
step "Di tab Kelas, buat satu kelas. Kodenya yang dibagikan ke siswa."
step "Di tab Data, tekan 'Terbitkan' supaya konten sampai ke siswa."
say ""
warn "Sebelum Terbitkan ditekan, siswa belum melihat materi apa pun."
pause "Tekan Enter untuk menutup wizard."

finish
